data:
  - attributes:
      created_at: '2021-10-27T13:20:58'
      destination_override_endpoint: 'https://echo.apps.verygood.systems'
      entries:
        - classifiers: {}
          config:
            condition: AND
            rules:
              - expression:
                  field: PathInfo
                  operator: matches
                  type: string
                  values:
                    - /post
              - expression:
                  field: ContentType
                  operator: equals
                  type: string
                  values:
                    - application/json
          id: 164c60f3-fb8c-48a3-afae-7b4e0408c2cf
          id_selector: null
          operation: REDACT
          operations: null
          phase: REQUEST
          public_token_generator: UUID
          targets:
            - body
          token_manager: VOLATILE
          transformer: JSON_PATH
          transformer_config:
            - $.card_cvc
          transformer_config_map: null
        - classifiers: {}
          config:
            condition: AND
            rules:
              - expression:
                  field: PathInfo
                  operator: equals
                  type: string
                  values:
                    - /post
              - expression:
                  field: ContentType
                  operator: equals
                  type: string
                  values:
                    - application/json
          id: c9017ce7-f587-4ff8-b2f9-8a6abb4cd9b0
          id_selector: null
          operation: REDACT
          operations: null
          phase: REQUEST
          public_token_generator: UUID
          targets:
            - body
          token_manager: PERSISTENT
          transformer: JSON_PATH
          transformer_config:
            - $.exp_date
          transformer_config_map: null
        - classifiers: {}
          config:
            condition: AND
            rules:
              - expression:
                  field: PathInfo
                  operator: equals
                  type: string
                  values:
                    - /post
              - expression:
                  field: ContentType
                  operator: equals
                  type: string
                  values:
                    - application/json
          id: b7160169-103b-425f-addf-c5e93b45661d
          id_selector: null
          operation: REDACT
          operations: null
          phase: REQUEST
          public_token_generator: UUID
          targets:
            - body
          token_manager: PERSISTENT
          transformer: JSON_PATH
          transformer_config:
            - $.cardholder_name
          transformer_config_map: null
        - classifiers: {}
          config:
            condition: AND
            rules:
              - expression:
                  field: PathInfo
                  operator: equals
                  type: string
                  values:
                    - /post
              - expression:
                  field: ContentType
                  operator: equals
                  type: string
                  values:
                    - application/json
          id: 47a2dedc-c76a-421d-8532-1f6238b8e52d
          id_selector: null
          operation: REDACT
          operations: null
          phase: REQUEST
          public_token_generator: UUID
          targets:
            - body
          token_manager: PERSISTENT
          transformer: JSON_PATH
          transformer_config:
            - $.card_number
          transformer_config_map: null
      host_endpoint: (.*)\.verygoodproxy\.com
      id: b97577e7-b010-4641-a9c5-47999b8c44e6
      ordinal: null
      port: 80
      protocol: http
      source_endpoint: '*'
      tags:
        name: Guide - Inbound
        source: Introduction Guide
        useCase: 'Other:Payments Optimization'
      updated_at: '2022-09-02T15:16:00'
    id: b97577e7-b010-4641-a9c5-47999b8c44e6
    type: rule_chain
version: 1
